server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:ep-ancient-salad-32171204.eu-central-1.aws.neon.fl0.io}:${PGPORT:5432}/${PGDATABASE:shortenurl}
    username: ${PGUSER:fl0user}
    password: ${PGPASSWORD:pTyI9faU2ohg}
  jpa:
    hibernate:
      ddl-auto: update

short-url:
  allowed-characters: ${ALLOWED_CHARS:abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789}
  key-length: ${KEY_LENGTH:6}